// ─── ShadowDrive AI — Core Data Types ───

/** A single line of dialogue in a language learning scenario */
export interface DialogueLine {
    id: number;
    /** Text in the target language (e.g. Dutch) */
    targetText: string;
    /** Text in the native language (e.g. English) */
    nativeText: string;
    /** Multiplier for pause duration. 1.0 = pause equals speech length */
    pauseMultiplier: number;
}

/** A complete scenario generated by Gemini */
export interface Scenario {
    title: string;
    /** BCP-47 language tag for target language, e.g. "nl-NL" */
    targetLang: string;
    /** BCP-47 language tag for native language, e.g. "en-US" */
    nativeLang: string;
    lines: DialogueLine[];
}

/** Playback phases for the audio engine */
export type PlaybackPhase = 'target' | 'pause' | 'native' | 'repeat' | 'gap';

/** Status yielded by the audio engine on each step */
export interface PlaybackStatus {
    lineIndex: number;
    totalLines: number;
    phase: PlaybackPhase;
    text: string;
    nativeText?: string;
}

/** Difficulty levels for scenario generation */
export type Difficulty = 'beginner' | 'intermediate' | 'advanced';

/** Request body for the /api/generate route */
export interface GenerateRequest {
    topic: string;
    difficulty: Difficulty;
}
