// ─── ShadowDrive AI — Core Data Types ───

/** A single line of dialogue in a language learning scenario */
export interface DialogueLine {
    id: number;
    /** Text in the target language (e.g. Dutch) */
    targetText: string;
    /** Text in the native language (e.g. Turkish) */
    nativeText: string;
    /** Multiplier for pause duration. 1.0 = pause equals speech length */
    pauseMultiplier: number;
}

/** A complete scenario generated by Gemini */
export interface Scenario {
    title: string;
    /** BCP-47 language tag for target language, e.g. "nl-NL" */
    targetLang: string;
    /** BCP-47 language tag for native language, e.g. "tr-TR" */
    nativeLang: string;
    lines: DialogueLine[];
}

/** Playback phases for the audio engine */
export type PlaybackPhase = "target" | "pause" | "listening" | "native" | "repeat" | "gap";

/** Result of a pronunciation recognition attempt */
export interface RecognitionResult {
    transcript: string;
    score: number;       // 0.0 - 1.0
    correct: boolean;
    supported: boolean;  // false = browser doesn't support speech recognition
}

/** Status yielded by the audio engine on each step */
export interface PlaybackStatus {
    lineIndex: number;
    totalLines: number;
    phase: PlaybackPhase;
    text: string;
    nativeText?: string;
    /** Present after a "listening" phase completes */
    recognitionResult?: RecognitionResult;
}

/** CEFR language proficiency levels */
export type CEFRLevel = "A0-A1" | "A2" | "B1" | "B2" | "C1-C2";

/** @deprecated Use CEFRLevel instead */
export type Difficulty = CEFRLevel;

/** Request body for the /api/generate route */
export interface GenerateRequest {
    topic: string;
    difficulty: CEFRLevel;
}

// ─── Auth & User Types ───

export interface User {
    id: number;
    email: string;
    displayName: string | null;
    createdAt: string;
}

export interface AuthResponse {
    token: string;
    user: User;
}

export interface RegisterRequest {
    email: string;
    password: string;
    displayName?: string;
}

export interface LoginRequest {
    email: string;
    password: string;
}

// ─── Progress & Favorites ───

export interface ProgressRecord {
    id: number;
    userId: number;
    lessonId: number;
    completed: boolean;
    completedAt: string | null;
}

export interface FavoriteRecord {
    id: number;
    userId: number;
    type: "course" | "scenario";
    targetId: number;
}

export interface CourseRecord {
    id: number;
    title: string;
    description: string | null;
    difficulty: CEFRLevel;
    targetLang: string;
    nativeLang: string;
}

export interface LessonRecord {
    id: number;
    courseId: number;
    title: string;
    order: number;
    lines: DialogueLine[];
}

// ─── Pronunciation & Progress Types ───

export interface PronunciationAttemptData {
    lessonType: "course" | "ai" | "custom";
    lessonId: string;
    lessonTitle: string;
    lineIndex: number;
    targetText: string;
    transcript: string;
    score: number;
    correct: boolean;
    recordingUrl?: string;
}

export interface LessonReportData {
    lessonType: "course" | "ai" | "custom";
    lessonId: string;
    lessonTitle: string;
    totalLines: number;
    correctCount: number;
    averageScore: number;
    attempts: PronunciationAttemptData[];
}

export interface ProfileStats {
    completedLessons: number;
    masteredLessons: number;
    pronunciationScore: number;
    dailyStreak: number;
    totalRepetitions: number;
    aiLessons: number;
    customLessons: number;
}

export interface UserGoalData {
    dailyTarget: number;
    weeklyTarget: number;
    todayCount: number;
    weekCount: number;
}

// ─── API Response Wrappers ───

export interface ApiError {
    error: string;
    details?: unknown;
}

export interface ApiSuccess<T> {
    data: T;
}

export interface PaginatedResponse<T> {
    data: T[];
    total: number;
    page: number;
    limit: number;
}
